# Generated by Django 5.2.8 on 2025-11-29 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.status'),
        ),
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
